version: '3'

services:
  dgep:
    build: .
    container_name: dgep
    ports:
      - "8888:80"
    volumes:
    - ./src:/app

  mongo:
    image: mongo
    container_name: dgep_mongo
    volumes:
    - ./mongo/data/db:/data/db
    ports:
    - "27017:27017"
