version: '3'

services:
  dgep:
    build: .
    container_name: dgep
    ports:
      - "8888:80"

  mongo:
    image: mongo
    container_name: dgep_mongo
    volumes:
    - dgep-mongo-volume:/data/db

volumes:
  dgep-mongo-volume:
   external: false
   driver: local
